spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java-cp5-2025-db
    username: postgres
    password: 120304
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  application:
    name: brinquedos-revisao

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    cache: false

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG